# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5c52fd7b70328378b9a37d03901b2315ccbeb230ee61323a66e66e79ca0d994b6b14dc3056a1ea94a8e5c0a10ebb16b10aaa9b324d28eb8ac2f1e3a82f37156

test:
  secret_key_base: 2c5027da84161204dae17293d8b91ff1fad97b8744be49699015058b8f24ac3a6a64c100dd97f51d743a417957c3f3fbeff6078d10f6fa99559957ea2f63a416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
